### ISSUE TITLE
Critical bug: model.save() overwrites entire directory contents

### ISSUE THREAD

**Issue by nicrie** [nicrie/xeofs#106]
**Describe the bug**
When specifying a directory instead of a file path to save a model, the function erroneously overwrites all data within the given directory. This behavior is not only unexpected but also extremely risky—I've just inadvertently lost files this way.

**Reproducible Minimal Working Example**

```python
import xeofs as xe
import xarray as xr

t2m = xr.tutorial.load_dataset("air_temperature")

model = xe.models.EOF()
model.fit(t2m, "time")
model.save("model.zarr")  # <-- that's fine

# WARNING: Executing the line below with a directory path will result in 
# the loss of all data within the specified directory. Use with extreme caution!
# --------------------------------------------------------------------------------------------
# Continue you if you feel that you have nothing to lose...
# model.save("/the/directory/you/might/accidentally/wipe/clean/")  # Hazardous usage!


```

**Expected behavior**
No data is overwritten.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - `xeofs` version: 2.0.0

I think that requires a quick fix @slevang. I will start working on a patch but please take extra caution when utilizing the save function in the meantime.

**Comment by slevang** [comment]
Oh wow, sorry about that! For whatever reason, I guess [DataTree.to_zarr()](https://xarray-datatree.readthedocs.io/en/latest/generated/datatree.DataTree.to_zarr.html) has a default of `mode="w"` which will indeed overwrite the directory contents if it already exists. [Dataset.to_zarr()](https://docs.xarray.dev/en/stable/generated/xarray.Dataset.to_zarr.html) has the much more sensible `mode="w-"` as default. This is in general a bit of a gotcha of xarray zarr writes (very easy to `rm -rf` a directory if you use `mode="w"`).

I can fix this in just a few minutes.

**Comment by nicrie** [comment]
Yes, I just noticed that too. The default value chosen by xarray-datatree seems to me to be quite recklessly chosen. ;)

**Comment by slevang** [comment]
> The default value chosen by xarray-datatree seems to me to be quite recklessly chosen. ;)

Very much so! I will propose this change there as well.

**Comment by nicrie** [comment]
> Very much so! I will propose this change there as well.

I already did, hoping to spare some other poor soul the feeling of digital Armageddon. Thanks for fixing this so quickly!

**Comment by slevang** [comment]
accidental deletions are no fun, hopefully it wasn't anything too catastrophic :fearful:

**Comment by nicrie** [comment]
I was in my "playground" folder. Lost a couple of files but nothing too important + there's a backup. Phew!
