### ISSUE TITLE
`dask`-based computation not entirely lazy

### ISSUE THREAD

**Issue by slevang** [nicrie/xeofs#109]
It's a bit of a shame that if working with a dask-backed dataset, we still end up eagerly executing the SVD with `Model(compute=False).fit(X)`. I found just 2 instances in the code (at least for EOFs) where we are forced to do computation because we can't do vectorized indexing with a dask array of indices ([#8958](https://github.com/dask/dask/issues/8958)):

1. is the sign flipping of the decomposition:
https://github.com/nicrie/xeofs/blob/1f38a5b818a5d5fc55720e1119e6f686aef89168/xeofs/models/decomposer.py#L157-L167

2. is the `Sanitizer` checks:
https://github.com/nicrie/xeofs/blob/1f38a5b818a5d5fc55720e1119e6f686aef89168/xeofs/preprocessing/sanitizer.py#L64-L74

There are also similar mandatory computes in the rotators and other models.

I don't see any immediate solutions to this, just noting that it would be a nice feature to have, especially for distributed workflows, e.g. building up a more complex calculation to submit to a cluster.

**Comment by slevang** [comment]
This also leads to some serious inefficiencies if we set `compute=False`, because we end up computing the SVD multiple times. With the current structure, it's unavoidable that we compute during the sign flip and then again when we compute the `DataContainer` objects. Although I wonder if this step could be moved as some postprocessing layer after whatever our first compute call is. May take some significant restructuring.

`DataContainer.compute()` is particularly inefficient though in this respect, because the loop will end up computing the SVD for each object we need to compute:
https://github.com/nicrie/xeofs/blob/1f38a5b818a5d5fc55720e1119e6f686aef89168/xeofs/data_container/data_container.py#L29-L36

Easily optimized with something like this, where `dask.compute` will optimize the task graph for all objects simultaneously:
```python
def compute(self, verbose=False):
        computed_data = {k: v for k, v in self.items() if self._allow_compute[k]}
        if verbose:
            with ProgressBar():
                computed_data = dask.compute(computed_data)[0]
        else:
            computed_data = dask.compute(computed_data)[0]
        for k, v in computed_data.items():
            self[k] = v
```

**Comment by nicrie** [comment]
Indeed,  off the top of my head, just some additional thoughts:

In the **Sanitizer**
* make the sanity check optional for those cases where we know/expect to not have any NaNs (cross-ref #83 )
* use `dask.compute()` to avoid redundant computations for `self.is_valid_feature` and `self.is_valid_sample`

I hoped that in many cases the decomposition result would fit into memory (say if you only need 10 modes).  In that case `compute=True` is already not too bad. Apart from the `Sanitizer` check there shouldn't be any redundant computations.

**Comment by nicrie** [comment]
I've made a [small tweak](https://github.com/nicrie/xeofs/commit/0c4225127f285a404af04c7078643a990f92961e) that eliminates at least one unnecessary computation. Feel free to push [to the branch](https://github.com/nicrie/xeofs/tree/nicrie/issue109) for any improvements regarding this issue.
