### ISSUE TITLE
provide dask support

### ISSUE THREAD

**Issue by nicrie** [nicrie/xeofs#11]

**Comment by miniufo** [comment]
Hi, its a nice package.  Do you have any clue on how to implement dask support?  Usually, the 3D data (2D space and 1D time) is chunked along time.  This may not be frendly for calculating covariance matrix, as it is a reduction operation along time dimension that cannot be a chunked.

**Comment by nicrie** [comment]
Hi Yu-Kun Qian - that's a good question, and one I've often asked myself as well. The way `xeofs` works right now is that it converts everything it gets into normal `numpy` arrays. All models are then implemented using pure `numpy` code. Although this has some advantages, it makes integration with `dask` a bit more difficult, since all the preprocessing steps (reshaping, weights, transformation, etc.) have to be implemented separately for `dask`.

Therefore, I finally decided to migrate `xeofs` from an "xarray wrapper based on Numpy models" to a "pure xarray" package that provides all the cool features of `xarray` (like `dask` support) for free. I am currently working on a new version that will include `dask` support, but that will certainly take some time.

Also note that the new version (`v1.0.0`) will contain **breaking changes**, most importantly support for `pandas` will be dropped. But since DataFrames can easily be converted to DataArrays, this should not cause any major problems. 

For now, I can only ask for patience until I finish the new release which will be hopefully soon :)

**Comment by miniufo** [comment]
> Therefore, I finally decided to migrate xeofs from an "xarray wrapper based on Numpy models" to a "pure xarray" package that provides all the cool features of xarray (like dask support) for free.

This is an exciting news for me, because I am looking for such eof package.  Numpy implementation is memory consuming if high-resolution data is used.  I guess the 'x' in 'xeofs' is best appreciated by its dask support.  Great job.
