### ISSUE TITLE
Add dependencies section in the documentation

### ISSUE THREAD

**Issue by malmans2** [nicrie/xeofs#132]
I suggest to add a dependencies section in the documentation.
`xarray`'s documentation is a good example: https://docs.xarray.dev/en/stable/getting-started-guide/installing.html#installation

JOSS review: https://github.com/openjournals/joss-reviews/issues/6060

**Comment by nicrie** [comment]
Thank you @malmans2  for the suggestion, that makes sense (underlined by the recent question in #134 ;) ) ! I just made a PR to address this.
