### ISSUE TITLE
numpy and pandas dependencies

### ISSUE THREAD

**Issue by arfriedman** [nicrie/xeofs#134]
Hi, apologies if this isn't the right place for this question -- I wasn't sure how to post a discussion:

In my conda, it appears that xeofs 2.1.0 is pinned to numpy<1.25 and pandas<2.0.0.
Is this requirement intended from xeofs, or is the issue from elsewhere?

Thanks much,
Andrew

**Comment by nicrie** [comment]
Hey! Thanks for asking – you're in the right place :) Until a few months ago, there was no support for `numpy` 1.25 from `numba`, but that has now been resolved (see [here](https://github.com/numba/numba/issues/9201)). There was a similar limitation with pandas at one point, but it seems to have been resolved, at least all tests run with the current versions of `numpy` and `pandas`. I'll release a new version without version restrictions in the coming days.

**Comment by arfriedman** [comment]
Great thanks!

**Comment by nicrie** [comment]
hey @arfriedman just a quick follow-up, the following releases will have relaxed version constraints on `numpy` and `pandas`. Until new releases are out you can already install the relaxed version of `xeofs`  from the `main` branch

```bash
pip install git+https://github.com/nicrie/xeofs.git
```
