### ISSUE TITLE
p-values of correlation measures are not FDR-corrected

### ISSUE THREAD

**Issue by nicrie** [nicrie/xeofs#26]
ideally the false discovery rate should be an argument provided to the method

**Comment by aaronspring** [comment]
we wrapped statsmodels multitests (fdr) [here](https://github.com/bradyrx/esmtools/blob/20c005d49fc1875288cf68c24bf61bd9487c0531/esmtools/testing.py#L13). feel free to copy if relevant as esmtools isnt really maintained anymore
