### ISSUE TITLE
Unable to install xeofs

### ISSUE THREAD

**Issue by GIRIJA-KALYANI** [nicrie/xeofs#29]
My issue currently is very basic.
I'm unable to install xeofs. I already have xMCA and eofs installed. Does that cause any issues?
Screenshot below (this is taking forever)

![image](https://user-images.githubusercontent.com/7091088/189530709-17a3d807-36b3-496d-bd8d-33f4c03796d5.png)

**Comment by Kastaway** [comment]
Hello, I am not sure but this might help https://github.com/conda/conda/issues/9367

**Comment by nicrie** [comment]
I think this is more related to conda and your environments than ``xeofs``. It's generally good practice to create and use different conda environments depending on your task. Try creating a new conda environment only with the packages you need, e.g.

``` py
conda create -n xeofs python=3.9
conda activate xeofs
conda install -c conda-forge xeofs
```

This should work :)

**Comment by GIRIJA-KALYANI** [comment]
> I think this is more related to conda and your environments than `xeofs`. It's generally good practice to create and use different conda environments depending on your task. Try creating a new conda environment only with the packages you need, e.g.
> 
> ```python
> conda create -n xeofs python=3.9
> conda activate xeofs
> conda install -c conda-forge xeofs
> ```
> 
> This should work :) Also, there shouldn't be any dependency issues with neither `eofs` nor `xmca`. It's probably because there are other packages in your base environment.

Thanks a lot, @nicrie Niclas, You're always of help.
It worked (As you said) :)

**Comment by GIRIJA-KALYANI** [comment]
> I think this is more related to conda and your environments than `xeofs`. It's generally good practice to create and use different conda environments depending on your task. Try creating a new conda environment only with the packages you need, e.g.
> 
> ```python
> conda create -n xeofs python=3.9
> conda activate xeofs
> conda install -c conda-forge xeofs
> ```
> 
> This should work :) Also, there shouldn't be any dependency issues with neither `eofs` nor `xmca`. It's probably because there are other packages in your base environment.

Thanks a lot @nicrie  Niclas, you're of timely help, as always.
And, it did work (As you said).

**Comment by nicrie** [comment]
Great, glad it worked :)

**Comment by GIRIJA-KALYANI** [comment]
Hi Niclas,
Post successful installation of xEOFs in a separate environment that by
default installs required most of the packages (presuming), I still have
issues with cartopy.
I see that cartopy, Proj, shapely are all installed, but I still get the
following error.
[image: image.png]
When I just started off with installations, I repeatedly got an error
saying "no module as cartopy" - so, I installed cartopy from
https://www.lfd.uci.edu/~gohlke/pythonlibs/#cartopy for my version of
python and windows. Later, the error continued with proj and shapely,
again, it was advised to install pyproj and shapely from the same link.
However, I wasn't yet successful with pyproj, but i can see proj :
[image: image.png]

However, while checking xEOFs - I can see the following (please note the
warnings)
[image: image.png]
Can you please suggest what could be causing these?
I'm unable to figure it out.
Thanks in advance!
Regards

Girija Kalyani Burada
PhD Student
School of Geography, Environment and Earth Sciences
Victoria University of Wellington
New Zealand

**Comment by nicrie** [comment]
Hi Girija,
Actually ``cartopy`` is not a dependency of ``xeofs`` - so you definitely want to install it in addition if you want to use ``cartopy``. 

Personally, I do not use windows but Linux, so I do not have experience with installing ``cartopy`` on your operating system. For me, installing ``cartopy`` together with ``xeofs`` from the ``conda-forge`` channel works without problems:

``` py
conda create -n xeofs python=3.9
conda activate xeofs
conda install -c conda-forge xeofs cartopy
```

Unfortunately, I cannot see the attached image. If you can please copy & paste the warning as text here.

**Comment by GIRIJA-KALYANI** [comment]
Well, this worked. 
Plots are great as I don't have to plot SVDs and hom_patterns separately like that of xMCA.
Thanks a lot.
Can you please share some references for understanding homogenous and nd heterogeneous patterns?
Mine looks this way :
![image](https://user-images.githubusercontent.com/7091088/189828137-69bd2013-905c-4ace-90be-0946b0824e2c.png)

**Comment by nicrie** [comment]
Perfect! For understanding a bit better the theory, check out Chapter 14.3 in Wilks' Statistical Methods in the Atmospheric Sciences or the paper by [Bretherton et al. 1992](https://journals.ametsoc.org/view/journals/clim/5/6/1520-0442_1992_005_0541_aiomff_2_0_co_2.xml?tab_body=abstract-display).

But in brief: Homogeneous patterns are just the correlation maps between the PCs and the corresponding input field (e.g. hom. pattern 1 = "**left**" field correlated **with** "**left**" PC1). Heterogeneous patterns represent the correlation maps between the PCs and the opposite input field (e.g. het. pattern 1 = "**left**" field correlated **with** "**right**" PC1).
