### ISSUE TITLE
Dark masked data in homogenous patterns 

### ISSUE THREAD

**Issue by GIRIJA-KALYANI** [nicrie/xeofs#30]
Hello Niclas,
I just worked on XEOFs and it works really well.
However, I have dark patches (or maybe masked stuff - refer screenshot below) in my homogenous patterns that are quite evident in the first 3 modes. These drop after 4th mode (2nd image)
![image](https://user-images.githubusercontent.com/7091088/196861120-b4085ea8-b6c0-4e95-bf67-89bf95ece70e.png)
![image](https://user-images.githubusercontent.com/7091088/196861337-7c3e5340-27d3-4907-805c-23fa09bffe5c.png)
Is it something that is usual? or is something wrong with my result? in both cases, what does that actually mean?

Also, where can I change the line plot to bar graphs for PCs?

**Comment by nicrie** [comment]
Just by looking at it: sorry no clue! If these were NaNs in the data they should be masked out consistently for different modes, but here the black patches are different for mode 2 and 4. Did you look into the underlying DataArrays to check what type of data it is? That could give you some hints on what you are looking at. 
Without any minimal working example or the raw data of your analysis, I cannot offer you more feedback, sorry!

**Comment by GIRIJA-KALYANI** [comment]
Well, thanks for the information on bars.
I think the masked regions aren't any errors. Looks like after changing transparency I relate they are based on p-values for homogenous and heterogenous arrays
![image](https://user-images.githubusercontent.com/7091088/197027195-7792dee0-c730-4d8f-9ccd-8651ee5eca16.png)
So, it all looks good, sorry for bothering - I came back here to delete the issue.
Another point (and if it is relevant to this) 
![image](https://user-images.githubusercontent.com/7091088/197027590-48e21c19-44a3-46a3-95c1-c7f76001dca6.png)

What does opposite i/p here mean?

**Comment by nicrie** [comment]
Ah! True, that makes sense if you use the p-values to mask the homogeneous patterns! :) 

Sorry for the somewhat unclear docstring of heterogeneous patterns. For two data fields X and Y, the homogeneous patterns calculate the correlations  corr(PC_x, X) and corr(PC_y, Y), while heterogeneous patterns are using the *opposite* field, i.e. corr(PC_x, Y) and corr(PC_y, X). Hope that's clear, if not don't hesitate to open another issue. I close this one as the original question was answered :)
