### ISSUE TITLE
project new "unseen" data to processed EOFS

### ISSUE THREAD

**Issue by simonweppe** [nicrie/xeofs#40]
Can the toolbox do that ?

For example : 
```
model = EOF(sst, n_modes=5, norm=False, dim=['lat', 'lon'])
model.solve()
expvar = model.explained_variance_ratio()
eofs = model.eofs()
pcs = model.pcs()
```

Then something 
```
model.transform(X)
```
which would yields the EOFs functions/values for each mode, for input array X

Thanks

**Comment by nicrie** [comment]
Indeed, you can achieve that by using the `.project_onto_eofs(X)` method.

I'd like to give you a heads up that in the upcoming weeks, I'll be rolling out a significant update - version 1. This version includes several major changes that may disrupt current functionalities. One noteworthy addition is a revamped API that mirrors the `sklearn` design pattern. As a result, you'll see familiar methods like `fit()` and `transform()`. This should make the interface more intuitive and user-friendly, especially for those already accustomed to using `sklearn`.

**Comment by simonweppe** [comment]
nice thanks @nicrie - will keep an eye for the update.

Thanks for the useful tool !
