### ISSUE TITLE
Differences from other packages?

### ISSUE THREAD

**Issue by navidcy** [nicrie/xeofs#47]
Would it be useful to include a small paragraph discussing the notable differences from other packages? E.g., I was wondering what's the difference from `eofs`.

**Comment by nicrie** [comment]
Hey Navid! Thanks for bringing that up, it's a really good question. I've taken the time to spruce up the Github landing page and added some more in-depth comparisons in the [documentation](https://xeofs.readthedocs.io/en/latest/overview.html). Hope it helps!

**Comment by navidcy** [comment]
Great!

**Comment by nicrie** [comment]
Oops, seems the updated docs didn't compile as expected. Seems I forgot to add the new pydata theme as a doc dependency. I'll make another PR with the updated environment which should fix it.

**Comment by nicrie** [comment]
it's online now: https://xeofs.readthedocs.io/en/latest/overview.html#comparison-with-other-packages
