### ISSUE TITLE
Weird scores amplitude weightening after MCA rotation

### ISSUE THREAD

**Issue by mschulzie** [nicrie/xeofs#65]
The scores' amplitude changes after adjusting of n_modes and achieves unexpected values. Seems to originate from a wrong "dim" argument within the mca rotator class (dot product between scores and rotation matrix, dim = mode instead of dim = mode1)

**Comment by nicrie** [comment]
Good catch @mschulzie will have a look into it!

**Comment by nicrie** [comment]
`transform` of `MCA` class is affected by the sae bug; can be fixed the same way though
