### ISSUE TITLE
Explained Local Variance EOF modes

### ISSUE THREAD

**Issue by fllamorim** [nicrie/xeofs#79]
Dear Niclas,

First, thank you so much for your xMCA and xeofs packages, they are excellent tools!
I am having a problem in defining the local explained variance, as in the following article:
https://www.researchgate.net/publication/252804054_A_coupled_bio-physical_model_HAMSOM-ECO_for_the_North_Sea_frontal_regions
It is more than a mathematical than programming problem, but I decided to ask your help because I am stuck on this.
I hope you can help me and I thank you in advance.

Best regards,

Felipe

**Comment by fllamorim** [comment]
Thank you very much, Niclas. I knew you would help me.
If you do not mind, I adapted your piece of code to my necessities and I will try to present to the authors of the study to verify the correctness.
Thank you again!

Best regards,

Felipe

**Comment by nicrie** [comment]
Glad it helped! :)
