### ISSUE TITLE
About compatibility of xeofs with other packages

### ISSUE THREAD

**Issue by liuchao95** [nicrie/xeofs#86]
The xeofs is awesome and user friendly, but I just wonder how many packages it can safely coexist with. I have found that it can cause compatibility problems when installing other packages, such as cdo or ncview. While I can wrap around by creating a new environment for the xeofs, I am just curious about its package dependencies.

**Comment by nicrie** [comment]
Thanks, @liuchao95! I don't see why `xeofs` would clash with either `cdo` or `ncview`. Could you share a simple example where you've run into these issues? It would help me figure out how to fix them and make everything work smoothly =)

**Comment by liuchao95** [comment]
Thank you for your response! It takes so long time to wait for the failure messages from the conda. After I change the internet environment, everything works fine now.
![image](https://github.com/nicrie/xeofs/assets/35416886/d51a9a40-d6f6-40f6-98fa-537fb168d1b9)
