### ISSUE TITLE
Convert the attributes type for easier export to netcdf format with the xarray.Dataset.to_netcdf method

### ISSUE THREAD

**Issue by liuchao95** [nicrie/xeofs#89]
The attributes of the MCA method output, has a "None" type and "bool" type, which are not directly compatible with the xr.DataArray.to_netcdf method. I wonder if it is possible to convert these None and Logical values to the String type to faciliate an easier export to netcdf format with the Xarray package, if these attributes are used only to record model configuration details.

![image](https://github.com/nicrie/xeofs/assets/35416886/2cced68f-d072-4d8b-b901-e0a8963c7904)

![image](https://github.com/nicrie/xeofs/assets/35416886/a82ce69f-4928-4825-83d3-b19b8155802c)

**Comment by nicrie** [comment]
Thank you for raising this! The attributes are indeed just for tracking model configurations, so you're probably right that converting all values to `str` will fix this. I'll try to make a new release in the coming days.

**Comment by liuchao95** [comment]
Thank you for your efforts in actively maintaining this package!

**Comment by nicrie** [comment]
No worries! I'll leave the issue open as a reminder for myself and until the new release is out.
